### PR TITLE
Run workflows MacOS and Ubuntu daily

### PR DESCRIPTION
**Pull request by wdconinc**
To catch breaking changes to the underlying platforms (e.g. https://github.com/cvmfs/cvmfs/issues/2882), run the testing workflow daily.

### CODE REVIEW

**Comment by wdconinc** [comment]
Case in point, MacOS fails right now...

**Comment by radupopescu** [comment]
Thanks for pinging me. I'll try to reproduce the failure.

**Comment by andresailer** [comment]
@wdconinc can you drop the 1015 check, and see if it works on macos 11?

**Comment by andresailer** [comment]
Add
```
    strategy:
      fail-fast: false
```
So if one fails the others aren't canceled?

**Comment by wdconinc** [comment]
Closed and reopened PR to trigger workflows.

**Pull request merged**
